Implement Indicate enchantment
teamfusion/spyglassplus pull request #4
Opened 2022-08-21 02:06 UTC by andantet

* [x] All entities glow when using indicate
* [x] Non-targeted entities' glows are dimmed
* [ ] Targeted entity of each player is synced to players tracking that player
  - Each client actively constructs a list of glowing entities?

2022-08-22 21:00 UTC, Dariensg requested changes
Most looks good! Just a couple things where I'm picky about not using wildcard imports for clarity.

2022-08-22 21:00 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/client/network/SpyglassPlusClientNetworking.java
> +import static com.github.teamfusion.spyglassplus.item.ISpyglass.*;
I typically discourage use of wildcard imports, so it would be great if you could switch this to non-wildcard

2022-08-22 21:00 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/mixin/client/EntityMixin.java
> +import java.awt.*;
Again with the wildcard

2022-08-23 10:02 UTC, andantet commented
I think if we're to change wildcards, we should do that separate to this PR. It's a whole-project thing at the moment.

2022-08-23 13:15 UTC, Dariensg requested changes

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/mixin/EntityMixin.java
> +import static com.github.teamfusion.spyglassplus.network.SpyglassPlusNetworking.*;
Wildcard

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/mixin/EntityMixin.java
> +                if (this.lastIndicateEntityId != -1) this.sendIndicateUpdate(CommonPlayerLookup.tracking(that), -1);
Changing one-lined if's into block if's would be great for clarity and readability

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/mixin/EntityMixin.java
> +        if (this.lastIndicateEntityId != id) this.sendIndicateUpdate(tracking, id);
One-lined if

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/mixin/LivingEntityMixin.java
> +import static com.github.teamfusion.spyglassplus.network.SpyglassPlusNetworking.*;
Wildcard

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/mixin/client/EntityMixin.java
> +        if (this.isGlowing()) return;
One-lined if

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/world/SpyglassRaycasting.java
> +        if (hit != null) distance = hit.getPos().squaredDistanceTo(min);
One-lined if

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/world/SpyglassRaycasting.java
> +            if (entityDistance < distance || hit == null) return entity;
One-lined if

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/world/SpyglassRaycasting.java
> +                if (!(runningDistance >= 0.0)) continue;
One-lined if

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/world/SpyglassRaycasting.java
> +            if (optional.isEmpty() || !((squaredDistance = min.squaredDistanceTo(runningPos = optional.get())) < runningDistance) && runningDistance != 0.0) continue;
One-lined if

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/world/SpyglassRaycasting.java
> +                if (runningDistance != 0.0) continue;
One-lined if

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/mixin/client/MouseMixin.java
> +import static com.github.teamfusion.spyglassplus.network.SpyglassPlusNetworking.*;
Wildcard

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/mixin/EntityMixin.java
> +        if (this.world.isClient) return;
One-lined if statement should be block

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/client/gui/DiscoveryHudRenderer.java
> +        if (this.targetedEntity != null) this.activeEntity = this.targetedEntity;
One-lined if needs to be a block

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/client/gui/DiscoveryHudRenderer.java
> +        if (DiscoveryHudRenderEvent.PRE.invoker().render(this, matrices, tickDelta, camera).isFalse()) return false;
One-lined if needs to be a block

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/client/entity/IndicateTargetManager.java
> +        if (id != -1) this.watchers.compute(id, (key, value) -> Math.max(0, (value == null ? 0 : value) - 1));
One-lined if needs to be a block

2022-08-23 13:15 UTC, Dariensg commented on common/src/main/java/com/github/teamfusion/spyglassplus/client/entity/IndicateTargetManager.java
> +        if (id != -1) this.watchers.compute(id, (key, value) -> (value == null ? 0 : value) + 1);
One-lined if needs to be a block

2022-08-24 09:38 UTC, merged